### ISSUE TITLE
Fresh installation aborts due to missing "libprotobuf-lite.so.25" package

### ISSUE THREAD

**Issue by spodermenpls** [llewelld/harbour-contrac#111]
I am using Contrac on a Sony Xperia XA2. Because of the recommendation of the Sailfish Updater, to uninstall Contrac before installing the latest Sailfish OS update, I removed it and wanted to re-install it after the update was done (now on 4.4.0.58 "Vanha Rauma").
 
To my surprise, the installation was not possible anymore, since according to the error description (as attached) a specific package called "libprotobuf-lite.so.25" is missing that Contrac relies on. Was this package part of Sailfish OS and having been removed / altered with OS version 4.4.0.58, resp. needs to be added to the installation package? Or may it been erroneously/accidentally removed during the uninstallation process before the OS update, unbeknownst to me?

![Bildschirmfoto_20220330_001](https://user-images.githubusercontent.com/23747593/166416719-06e61b75-61e9-4a70-bba8-cfb6c695637a.png)

**Comment by cnlpete** [comment]
@spodermenpls i have merged the appropriate fixes temporarily in my repo, you could use the github compiled rpm from my [forked-master](https://github.com/cnlpete/harbour-contrac/actions/runs/2140401645)

**Comment by bionade24** [comment]
The fix only is to recompile to the latest target, isn't it?

**Comment by spodermenpls** [comment]
> The fix only is to recompile to the latest target, isn't it?

@bionade24 Are you able to release the updated version on OpenRepos, or does only @llewelld have the credentials?

**Comment by bionade24** [comment]
Only @llewelld has access to OpenRepos currently. I'm already on the way of publishing it on Chum. I'm not sure how it'll go on with OpenRepos, I'll ask David to either oublish the new release or give me write rights to the OpenRepos package.

**Comment by bionade24** [comment]
I'm still closing this issue as it is fixed in the repo.

**Comment by bionade24** [comment]
@spodermenpls You can get the latest release *.rpm files from the release page, built by the CI until the packages are in chum: https://github.com/llewelld/harbour-contrac/releases/tag/0.7.8-1

**Comment by spodermenpls** [comment]
@bionade24 There's something wrong with your Chum version, the UI looks like this:

![Bildschirmfoto_20220512_001](https://user-images.githubusercontent.com/23747593/168130113-57215dfc-1744-4997-9aa9-68442677697e.png)

**Comment by bionade24** [comment]
@spodermenpls  #115 will fix this.

**Comment by spodermenpls** [comment]
@bionade24 @cnlpete Thanks for both of your work, now it works fine again.
