### ISSUE TITLE
MIssing "sailfishsecrets" in .spec file

### ISSUE THREAD

**Issue by philter1980** [llewelld/harbour-contrac#112]
In order to build the app for aarch64 it is needed to add "sailfishsecrets" in BuildRequires:  pkgconfig(sailfishsecrets) list inside harbour-contrac.spec

**Comment by cnlpete** [comment]
@philter1980 i have merged the appropriate fixes temporarily in my repo, you could use the github compiled rpm from my [forked-master](https://github.com/cnlpete/harbour-contrac/actions/runs/2140401645)

**Comment by bionade24** [comment]
Fix merged.
