### ISSUE TITLE
Received keys are not stored after restart

### ISSUE THREAD

**Issue by cintema** [llewelld/harbour-contrac#71]
I was using your app quite for a while, started to use it even when it did not sync to the official servers yet.
I had a few thousend keys received. I noted that, after restart of the phone, the received keys count would start at a certain number (4735 or something) again and again, even though many more keys were received in the meantime. I reinstalled the app but no sucess. I deleted everything, including the files in .local and .config. Now, the app would start counting from 0. However, when I restart the phone, it would start counting from 0 again. Is there anything else I could remove/reset?
Thank you!

**Comment by dimpflmoser** [comment]
It happened to me as well a few times, however the number of keys wasn't reset to 0 but to a lower number. Also I could not reproduce it, so I closed issue #66 again.

**Comment by dryo** [comment]
I suspect this is the same issue as #61

**Comment by cintema** [comment]
I can easily reproducw this issue by simply killing contracd with e.g. crest and then restarting it through harbor-contrac. I guess the database is not stored if the application terminates unexpectedly. Maybe even the data gets corrupted then, that even after a clean exit no updated databases can be stored any longer?

**Comment by andywuest** [comment]
I have experienced the same problem. Received keys are not stored on my device as well - and always restarts at a certain number.

**Comment by llewelld** [comment]
With the merging of #86, this has now been fixed thanks to @bionade24's good work. They settings file is now saved on periodically to ensure changes are maintained even if contracd crashes for some reason.
