### ISSUE TITLE
Add periodic automatic diagnosis key download

### ISSUE THREAD

**Issue by llewelld** [llewelld/harbour-contrac#78]
As a user, I'd like diagnosis keys to be downloaded automatically every day, so that I don't have to remember to do it myself.

Currently the user has to trigger a download of the diagnosis keys every day. A configuration option should be added to automatically trigger a download of the keys daily at a time set by the user.

**Comment by llewelld** [comment]
Ideally the download should run even if the app isn't running, but in practice it doesn't make sense architecturally to add this functionality to the daemon (it's not GAEN functionality), and so it'll be easier to just require the app to be running, rather than creating a whole new separate daemon for the process.

**Comment by llewelld** [comment]
Draft PR to add support for this: #81.

**Comment by dimpflmoser** [comment]
Would it be an option to have a systemd timer that triggers once a day to check if the app is running. If not it could launch the app. The app could terminate itself after the key update if it has been launched by systemd.

**Comment by llewelld** [comment]
I was originally planning to use timed for this, but a bug in timed (requesting timed to call a dbus method is broken at the moment) prevented it from working. I submitted a PR to fix timed here: https://git.sailfishos.org/mer-core/timed/merge_requests/25

However, @spiiroin (main timed dev) suggested it's probably better for this functionality to be dropped from timed entirely, and to use [nemo-qml-plugins-keepalive](https://sailfishos.org/develop/docs/nemo-qml-plugins-keepalive/qml-nemo-keepalive-backgroundjob.html) instead, so I'll look into that.

**Comment by llewelld** [comment]
MR #81 introduces this feature, so you can set keys to download every day at a particular time. At the moment the app has to be running for the download to take place.

@dimpflmoser: I like your idea, but I'm going to close this now and have created the separate task #94 to have the trigger work even if the app is closed.
