### ISSUE TITLE
Optimise diagnosis key risk calculation

### ISSUE THREAD

**Issue by llewelld** [llewelld/harbour-contrac#79]
Currently the risk calculation (when diagnosis keys are downloaded from the server and compared against received keys) takes a long time, often tens of minutes or hours depending on how many diagnosis keys are received from the server.

This can be disconcerting for the user, so it would be good to try to optimise the algorithm to speed it up.

I'd be interested to know whether people consider this to be a real problem or not. It's safe to let the calculation just run in the background, and maybe a solution such as adding a notification would be better (see #75). Please feel free to add your thoughts here.

**Comment by llewelld** [comment]
Some possible options for optimisation:
1. DTKs are processed in batches (currently set to batches of 1024). If `DayStorage::findDtkMatches()` was split into `initialiseFiltering()`, `findDtkMatch()`, `finaliseFiltering()` methods, the batching could be removed.
2. To avoid raceconditions when an RPI is received via Bluetooth, the bloom filter is currently locked for each batch of 144 RPIs. The bloom filter isn't particularly large, so it would be more efficient to make a copy of the filter at the start and avoid the need to lock it during testing.
3. Profile to establish what's taking longest: batching; generating RPIs from DTKs; or matching RPIs against the bloom filter. Focus on optimising the most resource-intensive part.

**Comment by dimpflmoser** [comment]
> I'd be interested to know whether people consider this to be a real problem or not. It's safe to let the calculation just run in the background, and maybe a solution such as adding a notification would be better (see #75). Please feel free to add your thoughts here.

I don't really care if it takes 10 secs or 1 hour. Initially I asked myself whether there's something wrong when processing didn't finish after the usual (previous) time span. Maybe it would be an option to show progress such as `x of y keys` checked.

**Comment by Matzt** [comment]
I agree with dimpflmoser. It's rather a nice to have feature.

**Comment by bionade24** [comment]
I disagree with you. I haven't downloaded any keys for over a month and now it runs for more than one hour. Some performance optimization would be nice, but I don't think that all effort has to spend on this.

**Comment by meisteredermeistereder-the-second** [comment]
Maybe you could borrow code from [https://github.com/mh-/corona-warn-companion-android](https://github.com/mh-/corona-warn-companion-android)?
This is quite fast. It downloads Diagnosis Keys and compares them with the keys stored in the database. On my FP3 it takes about two minutes or so, while on the XA2 contrac takes several hours and eats huge amounts of battery.

**Comment by chbmeyer** [comment]
Hello David and others,
I also want to say that waiting is not THAT important, but currently it exceeds all tolerance and makes contrac really useless. :(

Currently there are around 10.000 warning persons per day in germany (with of course much more Temporary Exposure Keys) and my phone (Sony Xperia 10) displays that it had sent nearly 40.000 keys while it had received 130.000.
I started the current 'daily update' 25 hours ago and it still says 'updating/refreshing'. I have no glue how long it will take to finish, but latest successful update is from Oct., 18th, nearly two months ago.

While incidence is increasing and Covid19 is coming nearer and nearer there is a real need of reliable warnings.
Can you please have a look at a faster matching algorithm?

Thanks a lot
Christian
