### ISSUE TITLE
postun tries to remove /home/deploy/installroot/usr/share/applications/*.desktop

### ISSUE THREAD

**Issue by vigejolla** [llewelld/harbour-contrac#88]
Pretty much what the title says.

**Comment by bionade24** [comment]
What's postun? postuninstall ?

**Comment by bionade24** [comment]
When I look in postun I can't find the wrong section, could you please point out? https://github.com/llewelld/harbour-contrac/blob/master/rpm/harbour-contrac.spec

Nevermind, found it.

**Comment by vigejolla** [comment]
Just in case: I'm quite sure it's this line: https://github.com/llewelld/harbour-contrac/blob/68fb73902367e89790223cc3f394fd1cdb416a13/rpm/harbour-contrac.spec#L89

**Comment by llewelld** [comment]
Thanks for flagging this up @vigejolla. Am I understanding correctly that the reason for the call in the first place is just to validate the contents of the desktop file?

This hopefully fixes it: https://github.com/llewelld/harbour-contrac/pull/89
